name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # agrega linux-latest si quieres
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build:web

      - name: Build Electron (electron-builder)
        run: npx electron-builder --publish never
        # call electron-builder directly via npx and explicitly disable publish
        env:
          GH_TOKEN: ''

      - name: List build outputs (debug)
        if: always()
        shell: pwsh
        run: |
          Write-Host "Contents of dist-electron:"
          if (Test-Path "./dist-electron") {
            Get-ChildItem "./dist-electron" -Recurse -Force | ForEach-Object { Write-Host $_.FullName }
          } else {
            Write-Host "no dist-electron"
          }

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GridieBlocks-Installer
          path: |
            dist-electron/GridieBlocks.Setup.1.0.0.exe

      - name: Create GitHub Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            dist-electron/GridieBlocks.Setup.1.0.0.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
