name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # agrega linux-latest si quieres
        node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build:web

      - name: Build Electron (electron-builder)
        run: npm run build:electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # para publicar si lo habilitas en electron-builder
          # Añade aquí secrets para firma de código si aplican: CSC_LINK, CSC_KEY_PASSWORD, etc.

      - name: Create GitHub Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist-electron/**/*.exe
            dist-electron/**/*.zip
